### ISSUE TITLE
As a patient, I would like to update my status so that my doctor is aware of my COVID status and symptoms

### ISSUE THREAD

**Issue by DrakeHunterK7** [AC159/SOEN_390#1]
### **Description:**

As a patient, I would like to access the status update form and be able to put in all the information about my covid symptoms. 

### **Steps:**

- [x] Add a Login page which redirects the user to the appropriate home page depending on user type.
- [x] Implement user profiles with associated user data. 
- [x] Add an "Update Status" page containing a form. 
- [x] Validate the data entered on this form to make sure everything entered is appropriate and reasonable.
- [x] Create a page that shows the patient their latest status report. 

### **Acceptance Test Steps:**

- Log in using patient credentials and land on the patient home page
- Click on the "Update Status" tab to go to the Update Status form
- Enter in the requested information and click Submit
- Wait for the confirmation message the confirms that the info was successfully sent to the patient's doctor. 
- Go to the home page and click on the "Your Latest Status Report"
- The information on this page should be the same as the info you just entered in the "Update Status" page form.
