### ISSUE TITLE
 As a patient, I would like to send my doctor messages so that I can communicate with my doctor about my health.

### ISSUE THREAD

**Issue by DrakeHunterK7** [AC159/SOEN_390#2]
### **Description:**

As a patient, I would like to be able to communicate with my doctor and ask them for advice, update them on my status report and convey a priority message to them in case of an urgent development.

### **Steps:**

- [x] Add a Login page which redirects the user to the appropriate home page depending on user type.
- [ ] Implement a Chat App where we can send regular or priority messages to recipients. 
- [ ] Implement user profiles with associated user data. 

### **Acceptance Test Steps:**

- Log in using patient credentials and land on the patient home page.
- Click on the chatbox and send a regular message to your doctor.
- Log in using the doctor's credentials and check if you have a message from the patient. Respond to it. 
- Log in again using patient credentials.
- Click on the chatbox and check if you received a response back by the doctor. Now, send a priority message.
- Log in again as the doctor and see if you have a priority message. Verify that the priority message looks different from the previous regular message.
