### ISSUE TITLE
As a patient, I would like to receive notifications about appointments, messages and alerts so that I don’t miss important communication. 

### ISSUE THREAD

**Issue by DrakeHunterK7** [AC159/SOEN_390#3]
### **Description:**

As a patient, I would like to receive notifications regarding any doctor appointments, exposure alerts and messages so that I don't miss any important communication. 

### **Steps:**

- [ ] Add a Login page which redirects the user to the appropriate home page depending on user type.
- [ ] Implement user profiles with associated user data. 
- [ ] Add a Notifications page that collects all sorts of notifications and possibly options for each type of notifications. Each notification should be clickable and should redirect to the corresponding page for that type of notification. 

### **Acceptance Test Steps:**

- Log in using patient credentials and land on the patient home page
- Click on the "Notifications" tab and verify if there are notifications
- Click on every type of notification and verify if you are redirected to the specific page for it.

**Comment by DrakeHunterK7** [comment]
This is a duplicate issue and will now be closed.
