### ISSUE TITLE
As a medical doctor, I would like to schedule appointments with my patients so that I can talk to them one-on-one. 

### ISSUE THREAD

**Issue by DrakeHunterK7** [AC159/SOEN_390#4]
### **Description:**

As a medical doctor, I would like to schedule appointments with my patients. 

### **Steps:**

- [x] Add a Login page which redirects the user to the appropriate home page depending on user type.
- [x] Implement user profiles with associated user data. 
- [x] Create a "Book an Appointment" page where the doctor can select a patient and book an appointment with them. 
- [x] Send a notification of this appointment to the corresponding patient
- [x] Store appointment data on the database and fetch this data when requested. 

### **Acceptance Test Steps:**

- Log in using doctor credentials and land on the doctor home page.
- Click on the "Book an Appointment" tab to go to the Appointment booking page. 
- Enter in the required information and click "Book Appointment".
- Log in as the patient.
- Go to the notification page and see if there is a notification for an appointment. Verify appointment information. 
- The information on this page should be the same as the info you just entered in the "Update Status" page form.

**Comment by p-carrier** [comment]
This is what I'm thinking about for Book an appointment.
This is the object that will be sent from the book appointment form:
```javascript
{
    patientId: <userId>,
    doctorId: <userId>,
    title: <string>,
    information: <string>,
    date: <date>,
    time: <time>
}
```
These are the things that we could modify:
- date and time could be saved as a timestamp too. 
- add the name of the patient and the doctor to simplify following query to indicate the doctor with whom the patient has a meeting and with which patient that doctor has a meeting.

What do you think?

**Comment by mth-1012** [comment]
From what I understand, title is like "Appointment with Dr. L on March 3rd", information is like "Dr. L wants to talk to you about...", right? And if the appointment is on Zoom, we can add a _**link**_ attribute so the front-end can do a "Join Meeting" button. Other than that, what you mentioned are all we need I believe.

**Comment by p-carrier** [comment]
I like that zoom meeting element. Maybe we should add a form in the doctor profile for the them to add their zoom meeting url? Regardless, this will be the information send as a notification to the patient.

```javascript
{
    title: 'Appointment with Dr. L on March 3rd',
    message: 'Dr. L wants to talk to you about...',
    zoomLink: 'https://zoom.us/<zoom-session-id>',
    timestamp: 123456789
}
```

**Comment by p-carrier** [comment]
@j-5844 @ani-6292 ,
this is how I think the post request should be done:

1.  The post will be send to this url: https://localhost:3000/doctor/<doctorId>/appointment, where <doctorId> is the id of the doctor creating an appointment
2. This is the object send by the request:
```javascript
{
    patientId: <userId>,
    title: <string>,
    information: <string>,
    date: <date>,
    time: <time>
}
```
